// Copyright (c) 2021 rookie-ninja
//
// Use of this source code is governed by an Apache-style
// license that can be found in the LICENSE file.
package rkginmeta

import (
	"github.com/gin-gonic/gin"
	"github.com/rookie-ninja/rk-common/common"
	"github.com/rookie-ninja/rk-entry/entry"
	"github.com/rookie-ninja/rk-gin/interceptor"
	"github.com/rookie-ninja/rk-gin/interceptor/context"
	"time"
)

// Add common headers as extension style in http response.
// The key is defined as bellow:
// 1: X-Request-Id: Request id generated by interceptor.
// 2: X-<Prefix-App: Application name.
// 3: X-<Prefix>-App-Version: Version of application.
// 4: X-<Prefix>-App-Unix-Time: Unix time of current application.
// 5: X-<Prefix>-Request-Received-Time: Time of current request received by application.
func Interceptor(opts ...Option) gin.HandlerFunc {
	set := newOptionSet(opts...)

	return func(ctx *gin.Context) {
		ctx.Set(rkgininter.RpcEntryNameKey, set.EntryName)

		requestId := rkcommon.GenerateRequestId()
		ctx.Header(rkginctx.RequestIdKey, requestId)

		event := rkginctx.GetEvent(ctx)
		event.SetRequestId(requestId)
		event.SetEventId(requestId)

		ctx.Header(set.AppNameKey, rkentry.GlobalAppCtx.GetAppInfoEntry().AppName)
		ctx.Header(set.AppVersionKey, rkentry.GlobalAppCtx.GetAppInfoEntry().Version)

		now := time.Now()
		ctx.Header(set.AppUnixTimeKey, now.Format(time.RFC3339Nano))
		ctx.Header(set.ReceivedTimeKey, now.Format(time.RFC3339Nano))

		ctx.Next()
	}
}
